### ISSUE TITLE
Done't reconnect after app restart 

### ISSUE THREAD

**Issue by imtianx** [trustwallet/wallet-connect-kotlin#57]
Using `WCSessionStoreType` to save the connect informations, after app restart, update sessions to reconnect. It  can't reconnect.

**Comment by imtianx** [comment]
After restarting app, create new WebSocket  using the cached session ,then reconnect  and update session.

**Comment by gmuresan** [comment]
@imtianx can you describe how you solved this problem?

I am trying to do something like this
```

    init {
        sessionStore = WCSessionStoreType(preferences)
    }

    fun start() {
        wcSession = sessionStore.session?.session ?: null
        if(wcSession != null) {
            wcClient.connect(wcSession!!, peerMeta)
            wcClient.updateSession(listOf("0x90F77d058AF9C48892CA6d06f7166037aF887857"), 1, true)
        }
    }
```

**Comment by imtianx** [comment]
Is that so, save the session and reconnect.[This is my simple modified code](
https://github.com/imtianx/wallet-connect-kotlin/blob/dapp/walletconnect/src/main/java/com/imtianx/walletconnect/WCClientManager.kt#L41-L66)

**Comment by gmuresan** [comment]
I figured out my issue for future users.
After you connect, the peerId and remotePeerId will get set on the WCClient object. Those 2 ids need to be saved and used as arguments in the WCClient.connect function
